// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestLoadBalancer.Data;

namespace TestLoadBalancer.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20210728045921_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestLoadBalancer.Data.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "Pass",
                            UserName = "UserName"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Pass2",
                            UserName = "UserName2"
                        },
                        new
                        {
                            Id = 3,
                            Password = "Pass3",
                            UserName = "UserName3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
